 * Serving Flask app "app"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/flask/cli.py", line 852, in run_command
    run_simple(
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/home/vagrant/.cache/pypoetry/virtualenvs/todo-app-vs8V2ZPt-py3.8/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/home/vagrant/.pyenv/versions/3.8.3/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/vagrant/.pyenv/versions/3.8.3/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/vagrant/.pyenv/versions/3.8.3/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
